defaults:
  - _self_
  - task: enzyme_class
  - representation: graph
  - model: ${representation}
  - training: default
  - paths: default
  - optional best_model: ${task}_${representation}
  - debug: null

general:
  seed: 0